#![allow(non_snake_case)]

// Re-export split-case test modules
#[path = "cases/case_001_cache_profile.rs"]
pub mod case_001_cache_profile;
#[path = "cases/case_002_cache_order.rs"]
pub mod case_002_cache_order;
#[path = "cases/case_003_cache_invoice.rs"]
pub mod case_003_cache_invoice;
#[path = "cases/case_004_cache_shipment.rs"]
pub mod case_004_cache_shipment;
#[path = "cases/case_005_cache_ticket.rs"]
pub mod case_005_cache_ticket;
#[path = "cases/case_006_cache_subscription.rs"]
pub mod case_006_cache_subscription;
#[path = "cases/case_007_publish_session.rs"]
pub mod case_007_publish_session;
#[path = "cases/case_008_publish_inventory.rs"]
pub mod case_008_publish_inventory;
#[path = "cases/case_009_publish_forecast.rs"]
pub mod case_009_publish_forecast;
#[path = "cases/case_010_publish_ledger.rs"]
pub mod case_010_publish_ledger;
#[path = "cases/case_011_publish_profile.rs"]
pub mod case_011_publish_profile;
#[path = "cases/case_012_publish_order.rs"]
pub mod case_012_publish_order;
#[path = "cases/case_013_publish_invoice.rs"]
pub mod case_013_publish_invoice;
#[path = "cases/case_014_publish_shipment.rs"]
pub mod case_014_publish_shipment;
#[path = "cases/case_015_publish_ticket.rs"]
pub mod case_015_publish_ticket;
#[path = "cases/case_016_stage_subscription.rs"]
pub mod case_016_stage_subscription;
#[path = "cases/case_017_stage_session.rs"]
pub mod case_017_stage_session;
#[path = "cases/case_018_stage_inventory.rs"]
pub mod case_018_stage_inventory;
#[path = "cases/case_019_stage_forecast.rs"]
pub mod case_019_stage_forecast;
#[path = "cases/case_020_stage_ledger.rs"]
pub mod case_020_stage_ledger;
#[path = "cases/case_021_stage_profile.rs"]
pub mod case_021_stage_profile;
#[path = "cases/case_022_stage_order.rs"]
pub mod case_022_stage_order;
#[path = "cases/case_023_stage_invoice.rs"]
pub mod case_023_stage_invoice;
#[path = "cases/case_024_stage_shipment.rs"]
pub mod case_024_stage_shipment;
#[path = "cases/case_025_stage_ticket.rs"]
pub mod case_025_stage_ticket;
#[path = "cases/case_026_stage_subscription.rs"]
pub mod case_026_stage_subscription;
#[path = "cases/case_027_archive_session.rs"]
pub mod case_027_archive_session;
#[path = "cases/case_028_archive_inventory.rs"]
pub mod case_028_archive_inventory;
#[path = "cases/case_029_archive_forecast.rs"]
pub mod case_029_archive_forecast;
#[path = "cases/case_030_archive_ledger.rs"]
pub mod case_030_archive_ledger;
#[path = "cases/case_031_archive_profile.rs"]
pub mod case_031_archive_profile;
#[path = "cases/case_032_archive_order.rs"]
pub mod case_032_archive_order;
#[path = "cases/case_033_archive_invoice.rs"]
pub mod case_033_archive_invoice;
#[path = "cases/case_034_archive_shipment.rs"]
pub mod case_034_archive_shipment;
#[path = "cases/case_035_archive_ticket.rs"]
pub mod case_035_archive_ticket;
#[path = "cases/case_036_normalize_subscription.rs"]
pub mod case_036_normalize_subscription;
#[path = "cases/case_037_normalize_session.rs"]
pub mod case_037_normalize_session;
#[path = "cases/case_038_normalize_inventory.rs"]
pub mod case_038_normalize_inventory;
#[path = "cases/case_039_normalize_forecast.rs"]
pub mod case_039_normalize_forecast;
#[path = "cases/case_040_normalize_ledger.rs"]
pub mod case_040_normalize_ledger;
#[path = "cases/case_041_normalize_profile.rs"]
pub mod case_041_normalize_profile;
#[path = "cases/case_042_normalize_order.rs"]
pub mod case_042_normalize_order;
#[path = "cases/case_043_normalize_invoice.rs"]
pub mod case_043_normalize_invoice;
#[path = "cases/case_044_normalize_shipment.rs"]
pub mod case_044_normalize_shipment;
#[path = "cases/case_045_normalize_ticket.rs"]
pub mod case_045_normalize_ticket;
#[path = "cases/case_046_normalize_subscription.rs"]
pub mod case_046_normalize_subscription;
#[path = "cases/case_047_score_session.rs"]
pub mod case_047_score_session;
#[path = "cases/case_048_score_inventory.rs"]
pub mod case_048_score_inventory;
#[path = "cases/case_049_score_forecast.rs"]
pub mod case_049_score_forecast;
#[path = "cases/case_050_score_ledger.rs"]
pub mod case_050_score_ledger;
#[path = "cases/case_051_score_profile.rs"]
pub mod case_051_score_profile;
#[path = "cases/case_052_score_order.rs"]
pub mod case_052_score_order;
#[path = "cases/case_053_score_invoice.rs"]
pub mod case_053_score_invoice;
#[path = "cases/case_054_score_shipment.rs"]
pub mod case_054_score_shipment;
#[path = "cases/case_055_score_ticket.rs"]
pub mod case_055_score_ticket;
#[path = "cases/case_056_enrich_subscription.rs"]
pub mod case_056_enrich_subscription;
#[path = "cases/case_057_enrich_session.rs"]
pub mod case_057_enrich_session;
#[path = "cases/case_058_enrich_inventory.rs"]
pub mod case_058_enrich_inventory;
#[path = "cases/case_059_enrich_forecast.rs"]
pub mod case_059_enrich_forecast;
#[path = "cases/case_060_enrich_ledger.rs"]
pub mod case_060_enrich_ledger;
#[path = "cases/case_061_enrich_profile.rs"]
pub mod case_061_enrich_profile;
#[path = "cases/case_062_enrich_order.rs"]
pub mod case_062_enrich_order;
#[path = "cases/case_063_enrich_invoice.rs"]
pub mod case_063_enrich_invoice;
#[path = "cases/case_064_enrich_shipment.rs"]
pub mod case_064_enrich_shipment;
#[path = "cases/case_065_enrich_ticket.rs"]
pub mod case_065_enrich_ticket;
#[path = "cases/case_066_enrich_subscription.rs"]
pub mod case_066_enrich_subscription;
#[path = "cases/case_067_snapshot_session.rs"]
pub mod case_067_snapshot_session;
#[path = "cases/case_068_snapshot_inventory.rs"]
pub mod case_068_snapshot_inventory;
#[path = "cases/case_069_snapshot_forecast.rs"]
pub mod case_069_snapshot_forecast;
#[path = "cases/case_070_snapshot_ledger.rs"]
pub mod case_070_snapshot_ledger;
#[path = "cases/case_071_snapshot_profile.rs"]
pub mod case_071_snapshot_profile;
#[path = "cases/case_072_snapshot_order.rs"]
pub mod case_072_snapshot_order;
#[path = "cases/case_073_snapshot_invoice.rs"]
pub mod case_073_snapshot_invoice;
#[path = "cases/case_074_snapshot_shipment.rs"]
pub mod case_074_snapshot_shipment;
#[path = "cases/case_075_snapshot_ticket.rs"]
pub mod case_075_snapshot_ticket;
#[path = "cases/case_076_route_subscription.rs"]
pub mod case_076_route_subscription;
#[path = "cases/case_077_route_session.rs"]
pub mod case_077_route_session;
#[path = "cases/case_078_route_inventory.rs"]
pub mod case_078_route_inventory;
#[path = "cases/case_079_route_forecast.rs"]
pub mod case_079_route_forecast;
#[path = "cases/case_080_route_ledger.rs"]
pub mod case_080_route_ledger;
#[path = "cases/case_081_route_profile.rs"]
pub mod case_081_route_profile;
#[path = "cases/case_082_route_order.rs"]
pub mod case_082_route_order;
#[path = "cases/case_083_route_invoice.rs"]
pub mod case_083_route_invoice;
#[path = "cases/case_084_route_shipment.rs"]
pub mod case_084_route_shipment;
#[path = "cases/case_085_route_ticket.rs"]
pub mod case_085_route_ticket;
#[path = "cases/case_086_route_subscription.rs"]
pub mod case_086_route_subscription;
#[path = "cases/case_087_reconcile_session.rs"]
pub mod case_087_reconcile_session;
#[path = "cases/case_088_reconcile_inventory.rs"]
pub mod case_088_reconcile_inventory;
#[path = "cases/case_089_reconcile_forecast.rs"]
pub mod case_089_reconcile_forecast;
#[path = "cases/case_090_reconcile_ledger.rs"]
pub mod case_090_reconcile_ledger;
#[path = "cases/case_091_reconcile_profile.rs"]
pub mod case_091_reconcile_profile;
#[path = "cases/case_092_reconcile_order.rs"]
pub mod case_092_reconcile_order;
#[path = "cases/case_093_reconcile_invoice.rs"]
pub mod case_093_reconcile_invoice;
#[path = "cases/case_094_reconcile_shipment.rs"]
pub mod case_094_reconcile_shipment;
#[path = "cases/case_095_reconcile_ticket.rs"]
pub mod case_095_reconcile_ticket;
#[path = "cases/case_096__subscription.rs"]
pub mod case_096__subscription;
#[path = "cases/case_097__session.rs"]
pub mod case_097__session;
#[path = "cases/case_098__inventory.rs"]
pub mod case_098__inventory;
#[path = "cases/case_099__forecast.rs"]
pub mod case_099__forecast;
#[path = "cases/case_100__ledger.rs"]
pub mod case_100__ledger;
#[path = "cases/case_101_alias_shadow_cache_01.rs"]
pub mod case_101_alias_shadow_cache_01;
#[path = "cases/case_102_deferred_sink_gate_01.rs"]
pub mod case_102_deferred_sink_gate_01;
#[path = "cases/case_103_closure_chain_async_01.rs"]
pub mod case_103_closure_chain_async_01;
#[path = "cases/case_104_indirect_container_write_01.rs"]
pub mod case_104_indirect_container_write_01;
#[path = "cases/case_105_thread_handoff_late_01.rs"]
pub mod case_105_thread_handoff_late_01;
#[path = "cases/case_106_decoy_retained_string_01.rs"]
pub mod case_106_decoy_retained_string_01;
#[path = "cases/case_107_dead_branch_global_01.rs"]
pub mod case_107_dead_branch_global_01;
#[path = "cases/case_108_local_cache_named_retained_01.rs"]
pub mod case_108_local_cache_named_retained_01;
#[path = "cases/case_109_serialized_copy_only_01.rs"]
pub mod case_109_serialized_copy_only_01;
#[path = "cases/case_110_closure_no_escape_01.rs"]
pub mod case_110_closure_no_escape_01;
#[path = "cases/case_111_alias_shadow_cache_02.rs"]
pub mod case_111_alias_shadow_cache_02;
#[path = "cases/case_112_deferred_sink_gate_02.rs"]
pub mod case_112_deferred_sink_gate_02;
#[path = "cases/case_113_closure_chain_async_02.rs"]
pub mod case_113_closure_chain_async_02;
#[path = "cases/case_114_indirect_container_write_02.rs"]
pub mod case_114_indirect_container_write_02;
#[path = "cases/case_115_thread_handoff_late_02.rs"]
pub mod case_115_thread_handoff_late_02;
#[path = "cases/case_116_decoy_retained_string_02.rs"]
pub mod case_116_decoy_retained_string_02;
#[path = "cases/case_117_dead_branch_global_02.rs"]
pub mod case_117_dead_branch_global_02;
#[path = "cases/case_118_local_cache_named_retained_02.rs"]
pub mod case_118_local_cache_named_retained_02;
#[path = "cases/case_119_serialized_copy_only_02.rs"]
pub mod case_119_serialized_copy_only_02;
#[path = "cases/case_120_closure_no_escape_02.rs"]
pub mod case_120_closure_no_escape_02;
#[path = "cases/case_121_alias_shadow_cache_03.rs"]
pub mod case_121_alias_shadow_cache_03;
#[path = "cases/case_122_deferred_sink_gate_03.rs"]
pub mod case_122_deferred_sink_gate_03;
#[path = "cases/case_123_closure_chain_async_03.rs"]
pub mod case_123_closure_chain_async_03;
#[path = "cases/case_124_indirect_container_write_03.rs"]
pub mod case_124_indirect_container_write_03;
#[path = "cases/case_125_thread_handoff_late_03.rs"]
pub mod case_125_thread_handoff_late_03;
#[path = "cases/case_126_decoy_retained_string_03.rs"]
pub mod case_126_decoy_retained_string_03;
#[path = "cases/case_127_dead_branch_global_03.rs"]
pub mod case_127_dead_branch_global_03;
#[path = "cases/case_128_local_cache_named_retained_03.rs"]
pub mod case_128_local_cache_named_retained_03;
#[path = "cases/case_129_serialized_copy_only_03.rs"]
pub mod case_129_serialized_copy_only_03;
#[path = "cases/case_130_closure_no_escape_03.rs"]
pub mod case_130_closure_no_escape_03;
#[path = "cases/case_131_alias_shadow_cache_04.rs"]
pub mod case_131_alias_shadow_cache_04;
#[path = "cases/case_132_deferred_sink_gate_04.rs"]
pub mod case_132_deferred_sink_gate_04;
#[path = "cases/case_133_closure_chain_async_04.rs"]
pub mod case_133_closure_chain_async_04;
#[path = "cases/case_134_indirect_container_write_04.rs"]
pub mod case_134_indirect_container_write_04;
#[path = "cases/case_135_thread_handoff_late_04.rs"]
pub mod case_135_thread_handoff_late_04;
#[path = "cases/case_136_decoy_retained_string_04.rs"]
pub mod case_136_decoy_retained_string_04;
#[path = "cases/case_137_dead_branch_global_04.rs"]
pub mod case_137_dead_branch_global_04;
#[path = "cases/case_138_local_cache_named_retained_04.rs"]
pub mod case_138_local_cache_named_retained_04;
#[path = "cases/case_139_serialized_copy_only_04.rs"]
pub mod case_139_serialized_copy_only_04;
#[path = "cases/case_140_closure_no_escape_04.rs"]
pub mod case_140_closure_no_escape_04;
#[path = "cases/case_141_alias_shadow_cache_05.rs"]
pub mod case_141_alias_shadow_cache_05;
#[path = "cases/case_142_deferred_sink_gate_05.rs"]
pub mod case_142_deferred_sink_gate_05;
#[path = "cases/case_143_closure_chain_async_05.rs"]
pub mod case_143_closure_chain_async_05;
#[path = "cases/case_144_indirect_container_write_05.rs"]
pub mod case_144_indirect_container_write_05;
#[path = "cases/case_145_thread_handoff_late_05.rs"]
pub mod case_145_thread_handoff_late_05;
#[path = "cases/case_146_decoy_retained_string_05.rs"]
pub mod case_146_decoy_retained_string_05;
#[path = "cases/case_147_dead_branch_global_05.rs"]
pub mod case_147_dead_branch_global_05;
#[path = "cases/case_148_local_cache_named_retained_05.rs"]
pub mod case_148_local_cache_named_retained_05;
#[path = "cases/case_149_serialized_copy_only_05.rs"]
pub mod case_149_serialized_copy_only_05;
#[path = "cases/case_150_closure_no_escape_05.rs"]
pub mod case_150_closure_no_escape_05;
#[path = "cases/case_151_alias_shadow_cache_06.rs"]
pub mod case_151_alias_shadow_cache_06;
#[path = "cases/case_152_deferred_sink_gate_06.rs"]
pub mod case_152_deferred_sink_gate_06;
#[path = "cases/case_153_closure_chain_async_06.rs"]
pub mod case_153_closure_chain_async_06;
#[path = "cases/case_154_indirect_container_write_06.rs"]
pub mod case_154_indirect_container_write_06;
#[path = "cases/case_155_thread_handoff_late_06.rs"]
pub mod case_155_thread_handoff_late_06;
#[path = "cases/case_156_decoy_retained_string_06.rs"]
pub mod case_156_decoy_retained_string_06;
#[path = "cases/case_157_dead_branch_global_06.rs"]
pub mod case_157_dead_branch_global_06;
#[path = "cases/case_158_local_cache_named_retained_06.rs"]
pub mod case_158_local_cache_named_retained_06;
#[path = "cases/case_159_serialized_copy_only_06.rs"]
pub mod case_159_serialized_copy_only_06;
#[path = "cases/case_160_closure_no_escape_06.rs"]
pub mod case_160_closure_no_escape_06;
#[path = "cases/case_161_alias_shadow_cache_07.rs"]
pub mod case_161_alias_shadow_cache_07;
#[path = "cases/case_162_deferred_sink_gate_07.rs"]
pub mod case_162_deferred_sink_gate_07;
#[path = "cases/case_163_closure_chain_async_07.rs"]
pub mod case_163_closure_chain_async_07;
#[path = "cases/case_164_indirect_container_write_07.rs"]
pub mod case_164_indirect_container_write_07;
#[path = "cases/case_165_thread_handoff_late_07.rs"]
pub mod case_165_thread_handoff_late_07;
#[path = "cases/case_166_decoy_retained_string_07.rs"]
pub mod case_166_decoy_retained_string_07;
#[path = "cases/case_167_dead_branch_global_07.rs"]
pub mod case_167_dead_branch_global_07;
#[path = "cases/case_168_local_cache_named_retained_07.rs"]
pub mod case_168_local_cache_named_retained_07;
#[path = "cases/case_169_serialized_copy_only_07.rs"]
pub mod case_169_serialized_copy_only_07;
#[path = "cases/case_170_closure_no_escape_07.rs"]
pub mod case_170_closure_no_escape_07;
#[path = "cases/case_171_alias_shadow_cache_08.rs"]
pub mod case_171_alias_shadow_cache_08;
#[path = "cases/case_172_deferred_sink_gate_08.rs"]
pub mod case_172_deferred_sink_gate_08;
#[path = "cases/case_173_closure_chain_async_08.rs"]
pub mod case_173_closure_chain_async_08;
#[path = "cases/case_174_indirect_container_write_08.rs"]
pub mod case_174_indirect_container_write_08;
#[path = "cases/case_175_thread_handoff_late_08.rs"]
pub mod case_175_thread_handoff_late_08;
#[path = "cases/case_176_decoy_retained_string_08.rs"]
pub mod case_176_decoy_retained_string_08;
#[path = "cases/case_177_dead_branch_global_08.rs"]
pub mod case_177_dead_branch_global_08;
#[path = "cases/case_178_local_cache_named_retained_08.rs"]
pub mod case_178_local_cache_named_retained_08;
#[path = "cases/case_179_serialized_copy_only_08.rs"]
pub mod case_179_serialized_copy_only_08;
#[path = "cases/case_180_closure_no_escape_08.rs"]
pub mod case_180_closure_no_escape_08;
#[path = "cases/case_181_alias_shadow_cache_09.rs"]
pub mod case_181_alias_shadow_cache_09;
#[path = "cases/case_182_deferred_sink_gate_09.rs"]
pub mod case_182_deferred_sink_gate_09;
#[path = "cases/case_183_closure_chain_async_09.rs"]
pub mod case_183_closure_chain_async_09;
#[path = "cases/case_184_indirect_container_write_09.rs"]
pub mod case_184_indirect_container_write_09;
#[path = "cases/case_185_thread_handoff_late_09.rs"]
pub mod case_185_thread_handoff_late_09;
#[path = "cases/case_186_decoy_retained_string_09.rs"]
pub mod case_186_decoy_retained_string_09;
#[path = "cases/case_187_dead_branch_global_09.rs"]
pub mod case_187_dead_branch_global_09;
#[path = "cases/case_188_local_cache_named_retained_09.rs"]
pub mod case_188_local_cache_named_retained_09;
#[path = "cases/case_189_serialized_copy_only_09.rs"]
pub mod case_189_serialized_copy_only_09;
#[path = "cases/case_190_closure_no_escape_09.rs"]
pub mod case_190_closure_no_escape_09;
#[path = "cases/case_191_alias_shadow_cache_10.rs"]
pub mod case_191_alias_shadow_cache_10;
#[path = "cases/case_192_deferred_sink_gate_10.rs"]
pub mod case_192_deferred_sink_gate_10;
#[path = "cases/case_193_closure_chain_async_10.rs"]
pub mod case_193_closure_chain_async_10;
#[path = "cases/case_194_indirect_container_write_10.rs"]
pub mod case_194_indirect_container_write_10;
#[path = "cases/case_195_thread_handoff_late_10.rs"]
pub mod case_195_thread_handoff_late_10;
#[path = "cases/case_196_decoy_retained_string_10.rs"]
pub mod case_196_decoy_retained_string_10;
#[path = "cases/case_197_dead_branch_global_10.rs"]
pub mod case_197_dead_branch_global_10;
#[path = "cases/case_198_local_cache_named_retained_10.rs"]
pub mod case_198_local_cache_named_retained_10;
#[path = "cases/case_199_serialized_copy_only_10.rs"]
pub mod case_199_serialized_copy_only_10;
#[path = "cases/case_200_closure_no_escape_10.rs"]
pub mod case_200_closure_no_escape_10;
#[path = "cases/case_201_alias_hop_chain_01.rs"]
pub mod case_201_alias_hop_chain_01;
#[path = "cases/case_202_helper_sink_dispatch_01.rs"]
pub mod case_202_helper_sink_dispatch_01;
#[path = "cases/case_203_closure_registry_delay_01.rs"]
pub mod case_203_closure_registry_delay_01;
#[path = "cases/case_204_container_handoff_global_01.rs"]
pub mod case_204_container_handoff_global_01;
#[path = "cases/case_205_interface_sink_bridge_01.rs"]
pub mod case_205_interface_sink_bridge_01;
#[path = "cases/case_206_thread_pool_capture_01.rs"]
pub mod case_206_thread_pool_capture_01;
#[path = "cases/case_207_dead_sink_decoy_01.rs"]
pub mod case_207_dead_sink_decoy_01;
#[path = "cases/case_208_copy_then_drop_01.rs"]
pub mod case_208_copy_then_drop_01;
#[path = "cases/case_209_local_clone_named_retained_01.rs"]
pub mod case_209_local_clone_named_retained_01;
#[path = "cases/case_210_serialization_roundtrip_safe_01.rs"]
pub mod case_210_serialization_roundtrip_safe_01;
#[path = "cases/case_211_shadowed_sink_local_01.rs"]
pub mod case_211_shadowed_sink_local_01;
#[path = "cases/case_212_ephemeral_lambda_use_01.rs"]
pub mod case_212_ephemeral_lambda_use_01;
#[path = "cases/case_213_alias_hop_chain_02.rs"]
pub mod case_213_alias_hop_chain_02;
#[path = "cases/case_214_helper_sink_dispatch_02.rs"]
pub mod case_214_helper_sink_dispatch_02;
#[path = "cases/case_215_closure_registry_delay_02.rs"]
pub mod case_215_closure_registry_delay_02;
#[path = "cases/case_216_container_handoff_global_02.rs"]
pub mod case_216_container_handoff_global_02;
#[path = "cases/case_217_interface_sink_bridge_02.rs"]
pub mod case_217_interface_sink_bridge_02;
#[path = "cases/case_218_thread_pool_capture_02.rs"]
pub mod case_218_thread_pool_capture_02;
#[path = "cases/case_219_dead_sink_decoy_02.rs"]
pub mod case_219_dead_sink_decoy_02;
#[path = "cases/case_220_copy_then_drop_02.rs"]
pub mod case_220_copy_then_drop_02;
#[path = "cases/case_221_local_clone_named_retained_02.rs"]
pub mod case_221_local_clone_named_retained_02;
#[path = "cases/case_222_serialization_roundtrip_safe_02.rs"]
pub mod case_222_serialization_roundtrip_safe_02;
#[path = "cases/case_223_shadowed_sink_local_02.rs"]
pub mod case_223_shadowed_sink_local_02;
#[path = "cases/case_224_ephemeral_lambda_use_02.rs"]
pub mod case_224_ephemeral_lambda_use_02;
#[path = "cases/case_225_alias_hop_chain_03.rs"]
pub mod case_225_alias_hop_chain_03;
#[path = "cases/case_226_helper_sink_dispatch_03.rs"]
pub mod case_226_helper_sink_dispatch_03;
#[path = "cases/case_227_closure_registry_delay_03.rs"]
pub mod case_227_closure_registry_delay_03;
#[path = "cases/case_228_container_handoff_global_03.rs"]
pub mod case_228_container_handoff_global_03;
#[path = "cases/case_229_interface_sink_bridge_03.rs"]
pub mod case_229_interface_sink_bridge_03;
#[path = "cases/case_230_thread_pool_capture_03.rs"]
pub mod case_230_thread_pool_capture_03;
#[path = "cases/case_231_dead_sink_decoy_03.rs"]
pub mod case_231_dead_sink_decoy_03;
#[path = "cases/case_232_copy_then_drop_03.rs"]
pub mod case_232_copy_then_drop_03;
#[path = "cases/case_233_local_clone_named_retained_03.rs"]
pub mod case_233_local_clone_named_retained_03;
#[path = "cases/case_234_serialization_roundtrip_safe_03.rs"]
pub mod case_234_serialization_roundtrip_safe_03;
#[path = "cases/case_235_shadowed_sink_local_03.rs"]
pub mod case_235_shadowed_sink_local_03;
#[path = "cases/case_236_ephemeral_lambda_use_03.rs"]
pub mod case_236_ephemeral_lambda_use_03;
#[path = "cases/case_237_alias_hop_chain_04.rs"]
pub mod case_237_alias_hop_chain_04;
#[path = "cases/case_238_helper_sink_dispatch_04.rs"]
pub mod case_238_helper_sink_dispatch_04;
#[path = "cases/case_239_closure_registry_delay_04.rs"]
pub mod case_239_closure_registry_delay_04;
#[path = "cases/case_240_container_handoff_global_04.rs"]
pub mod case_240_container_handoff_global_04;
#[path = "cases/case_241_interface_sink_bridge_04.rs"]
pub mod case_241_interface_sink_bridge_04;
#[path = "cases/case_242_thread_pool_capture_04.rs"]
pub mod case_242_thread_pool_capture_04;
#[path = "cases/case_243_dead_sink_decoy_04.rs"]
pub mod case_243_dead_sink_decoy_04;
#[path = "cases/case_244_copy_then_drop_04.rs"]
pub mod case_244_copy_then_drop_04;
#[path = "cases/case_245_local_clone_named_retained_04.rs"]
pub mod case_245_local_clone_named_retained_04;
#[path = "cases/case_246_serialization_roundtrip_safe_04.rs"]
pub mod case_246_serialization_roundtrip_safe_04;
#[path = "cases/case_247_shadowed_sink_local_04.rs"]
pub mod case_247_shadowed_sink_local_04;
#[path = "cases/case_248_ephemeral_lambda_use_04.rs"]
pub mod case_248_ephemeral_lambda_use_04;
#[path = "cases/case_249_alias_hop_chain_05.rs"]
pub mod case_249_alias_hop_chain_05;
#[path = "cases/case_250_helper_sink_dispatch_05.rs"]
pub mod case_250_helper_sink_dispatch_05;
#[path = "cases/case_251_closure_registry_delay_05.rs"]
pub mod case_251_closure_registry_delay_05;
#[path = "cases/case_252_container_handoff_global_05.rs"]
pub mod case_252_container_handoff_global_05;
#[path = "cases/case_253_interface_sink_bridge_05.rs"]
pub mod case_253_interface_sink_bridge_05;
#[path = "cases/case_254_thread_pool_capture_05.rs"]
pub mod case_254_thread_pool_capture_05;
#[path = "cases/case_255_dead_sink_decoy_05.rs"]
pub mod case_255_dead_sink_decoy_05;
#[path = "cases/case_256_copy_then_drop_05.rs"]
pub mod case_256_copy_then_drop_05;
#[path = "cases/case_257_local_clone_named_retained_05.rs"]
pub mod case_257_local_clone_named_retained_05;
#[path = "cases/case_258_serialization_roundtrip_safe_05.rs"]
pub mod case_258_serialization_roundtrip_safe_05;
#[path = "cases/case_259_shadowed_sink_local_05.rs"]
pub mod case_259_shadowed_sink_local_05;
#[path = "cases/case_260_ephemeral_lambda_use_05.rs"]
pub mod case_260_ephemeral_lambda_use_05;
#[path = "cases/case_261_alias_hop_chain_06.rs"]
pub mod case_261_alias_hop_chain_06;
#[path = "cases/case_262_helper_sink_dispatch_06.rs"]
pub mod case_262_helper_sink_dispatch_06;
#[path = "cases/case_263_closure_registry_delay_06.rs"]
pub mod case_263_closure_registry_delay_06;
#[path = "cases/case_264_container_handoff_global_06.rs"]
pub mod case_264_container_handoff_global_06;
#[path = "cases/case_265_interface_sink_bridge_06.rs"]
pub mod case_265_interface_sink_bridge_06;
#[path = "cases/case_266_thread_pool_capture_06.rs"]
pub mod case_266_thread_pool_capture_06;
#[path = "cases/case_267_dead_sink_decoy_06.rs"]
pub mod case_267_dead_sink_decoy_06;
#[path = "cases/case_268_copy_then_drop_06.rs"]
pub mod case_268_copy_then_drop_06;
#[path = "cases/case_269_local_clone_named_retained_06.rs"]
pub mod case_269_local_clone_named_retained_06;
#[path = "cases/case_270_serialization_roundtrip_safe_06.rs"]
pub mod case_270_serialization_roundtrip_safe_06;
#[path = "cases/case_271_shadowed_sink_local_06.rs"]
pub mod case_271_shadowed_sink_local_06;
#[path = "cases/case_272_ephemeral_lambda_use_06.rs"]
pub mod case_272_ephemeral_lambda_use_06;
#[path = "cases/case_273_alias_hop_chain_07.rs"]
pub mod case_273_alias_hop_chain_07;
#[path = "cases/case_274_helper_sink_dispatch_07.rs"]
pub mod case_274_helper_sink_dispatch_07;
#[path = "cases/case_275_closure_registry_delay_07.rs"]
pub mod case_275_closure_registry_delay_07;
#[path = "cases/case_276_container_handoff_global_07.rs"]
pub mod case_276_container_handoff_global_07;
#[path = "cases/case_277_interface_sink_bridge_07.rs"]
pub mod case_277_interface_sink_bridge_07;
#[path = "cases/case_278_thread_pool_capture_07.rs"]
pub mod case_278_thread_pool_capture_07;
#[path = "cases/case_279_dead_sink_decoy_07.rs"]
pub mod case_279_dead_sink_decoy_07;
#[path = "cases/case_280_copy_then_drop_07.rs"]
pub mod case_280_copy_then_drop_07;
#[path = "cases/case_281_local_clone_named_retained_07.rs"]
pub mod case_281_local_clone_named_retained_07;
#[path = "cases/case_282_serialization_roundtrip_safe_07.rs"]
pub mod case_282_serialization_roundtrip_safe_07;
#[path = "cases/case_283_shadowed_sink_local_07.rs"]
pub mod case_283_shadowed_sink_local_07;
#[path = "cases/case_284_ephemeral_lambda_use_07.rs"]
pub mod case_284_ephemeral_lambda_use_07;
#[path = "cases/case_285_alias_hop_chain_08.rs"]
pub mod case_285_alias_hop_chain_08;
#[path = "cases/case_286_helper_sink_dispatch_08.rs"]
pub mod case_286_helper_sink_dispatch_08;
#[path = "cases/case_287_closure_registry_delay_08.rs"]
pub mod case_287_closure_registry_delay_08;
#[path = "cases/case_288_container_handoff_global_08.rs"]
pub mod case_288_container_handoff_global_08;
#[path = "cases/case_289_interface_sink_bridge_08.rs"]
pub mod case_289_interface_sink_bridge_08;
#[path = "cases/case_290_thread_pool_capture_08.rs"]
pub mod case_290_thread_pool_capture_08;
#[path = "cases/case_291_dead_sink_decoy_08.rs"]
pub mod case_291_dead_sink_decoy_08;
#[path = "cases/case_292_copy_then_drop_08.rs"]
pub mod case_292_copy_then_drop_08;
#[path = "cases/case_293_local_clone_named_retained_08.rs"]
pub mod case_293_local_clone_named_retained_08;
#[path = "cases/case_294_serialization_roundtrip_safe_08.rs"]
pub mod case_294_serialization_roundtrip_safe_08;
#[path = "cases/case_295_shadowed_sink_local_08.rs"]
pub mod case_295_shadowed_sink_local_08;
#[path = "cases/case_296_ephemeral_lambda_use_08.rs"]
pub mod case_296_ephemeral_lambda_use_08;
#[path = "cases/case_297_alias_hop_chain_09.rs"]
pub mod case_297_alias_hop_chain_09;
#[path = "cases/case_298_helper_sink_dispatch_09.rs"]
pub mod case_298_helper_sink_dispatch_09;
#[path = "cases/case_299_closure_registry_delay_09.rs"]
pub mod case_299_closure_registry_delay_09;
#[path = "cases/case_300_container_handoff_global_09.rs"]
pub mod case_300_container_handoff_global_09;
#[path = "cases/case_301_stealth_global_store_escape.rs"]
pub mod case_301_stealth_global_store_escape;
#[path = "cases/case_302_indirect_holder_escape.rs"]
pub mod case_302_indirect_holder_escape;
#[path = "cases/case_303_array_slot_escape.rs"]
pub mod case_303_array_slot_escape;
